spring:
  jmx:
    enabled: true
    unique-names: true
management:
  datadog:
    metrics:
      export:
        enabled: true
  info:
    env:
      enabled: true
    git:
      mode: full
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
    build:
      enabled: true
  endpoint:
    health:
      group:
        custom:
          include: "*"
          show-components: always
          show-details: always
    info:
      enabled: true
    env:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"
info:
  app:
    encoding: "@project.build.sourceEncoding@"
    java:
      source: "@java.version@"
      target: "@java.version@"