# Use root/example as user/password credentials
version: '3.1'

services:
#PERSISTENT STORAGE
  mongo:
    image: mongodb/mongodb-community-server:latest
    container_name: mongo
    restart: on-failure
    expose:
      - 27018
    ports:
      - 27018:27018
    networks:
      lan-java-mongo-prometheus-grafana:
        ipv4_address: 10.5.0.2
    user: "0"
    volumes:
      - ./data/mongo:/data/db:rw
      - ./data/mongo:/data/configdb:rw
      - ./docker-entrypoint/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    command: mongod --port 27018
  postgresql:
    image: postgres
    restart: always
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    expose:
      - 5433
    ports:
      - 5433:5433
    networks:
      lan-java-mongo-prometheus-grafana:
        ipv4_address: 10.5.0.3
    environment:
      POSTGRES_PASSWORD: "1234"
      POSTGRES_USER: "manager"
      POSTGRES_DB: "user_manager"
    command: -p 5433
  pg_export:
    image: bitnami/postgres-exporter:latest
    container_name: postgres-exporter
    expose:
      - 9187
    ports:
      - 9187:9187
    environment:
      DATA_SOURCE_NAME: "postgresql://manager:1234@10.5.0.3:5433/user_manager?sslmode=disable"
    networks:
      lan-java-mongo-prometheus-grafana:
        ipv4_address: 10.5.0.4
    volumes:
      - ./postgres_exporter.yml:/opt/bitnami/postgres-exporter/postgres_exporter.yml:ro
      #MONITORING
  grafana:
    image: grafana/grafana-enterprise:latest
    container_name: grafana
    restart: unless-stopped
    user: "0"
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./data/grafana:/etc/grafana/provisioning/
    expose:
      - 3000
    ports:
      - '3000:3000'
    networks:
      lan-java-mongo-prometheus-grafana:
        ipv4_address: 10.5.1.1
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=1234
      - GF_SECURITY_ADMIN_USER=admin
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./data/prometheus:/etc/prometheus/
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    container_name: prometheus
    hostname: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    expose:
      - 8090
      - 8091
    ports:
      - 9090:9090
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    networks:
      lan-java-mongo-prometheus-grafana:
        ipv4_address: 10.5.1.2
#APPLICATION
  messenger:
    image: messenger-java17:0.0.1-SNAPSHOT
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '200M'
    environment:
      SERVER_ADDRESS: "10.5.2.1"
      SERVER_PORT: "8081"
      MANAGEMENT_SERVER_PORT: "8990"
      SPRING_PROFILES_ACTIVE: "DEV"
      SPRING_BOOT_ADMIN_CLIENT_URL: "http://10.5.0.4:8082"
      SPRING_BOOT_ADMIN_CLIENT_INSTACE_NAME: "@project.artifactId@"
      SPRING_BOOT_ADMIN_CLIENT_INSTACE_ENABLED: "true"
      MANAGEMENT_HEALTH_DISKSPACE: "true"
      MANAGEMENT_INFO_ENV_ENABLED: "true"
      MANAGEMENT_INFO_GIT_MODE: "full"
      MANAGEMENT_INFO_GIT_ENABLED: "true"
      MANAGEMENT_INFO_OS_ENABLED: "true"
      MANAGEMENT_INFO_BUILD_ENABLED: "true"
      MANAGEMENT_ENDPOINT_HEALTH_SHOW-DETAILDS: "always"
      MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
      MANAGEMENT_ENDPOINT_INFO_ENABLED: "true"
      MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED: "true"
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "*"
      MANAGEMENT_ENDPOINTS_JMX_EXPOSURE_INCLUDE: "*"
      MANAGEMENT_ENDPOINTS_METRICS_ENABLE_ALL: "true"
      MANAGEMENT_INFO_ENABLED: "true"
    ports:
      - 8081:8081
      - 8990:8990
    networks:
      lan-java-mongo-prometheus-grafana:
        ipv4_address: 10.5.2.1
  user-manger:
    image: user-manager-java17:0.0.1-SNAPSHOT
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '200M'
    environment:
      SPRING_DATASOURCE_USERNAME: "manager"
      SPRING_DATASOURCE_PASSWORD: "1234"
      SPRING_DATASOURCE_HIKARI_CONNECTION-TIMEOUT: "50000"
      SPRING_DATASOURCE_HIKARI_IDLE-TIMEOUT: "300000"
      SPRING_DATASOURCE_HIKARI_MAX-LIFETIME: "900000"
      SPRING_DATASOURCE_HICKARI_MAXIMUM-POOL-SIZE: "5"
      SPRING_DATASOURCE_HICKARI_MINIMUM-IDLE: "3"
      SPRING_DATASOURCE_HICKARI_POOL-NAME: "UserManagerPool"
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: "org.postgresql.Driver"
      SPRING_DATASOURCE_TYPE: "com.zaxxer.hikari.HikariDataSource"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://10.5.0.3:5433/user_manager"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.PostgreSQLDialect"
      SPRING_JPA_HIBERNATE_DLL-AUTO: "update"
      SPRING_JPA_PROPERTIES_HIBERNATE_GENERATE_STATISTICS: "true"
      SPRING_JPA_HIBERNATE_CONNECTION_PROVIDER_CLASS: "org.hibernate.hikaricp.internal.HikariCPConnectionProvider"
      SPRING_JPA_SHOW-SQL: "true"
      JWT_SECRET_ACCESS: "qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w"
      JWT_SECRET_LIFE-TIME: "100"
      SERVER_ADDRESS: "10.5.2.2"
      SERVER_PORT: "8083"
      MANAGEMENT_SERVER_PORT: "8991"
      SPRING_PROFILES_ACTIVE: "DEV"
      SPRING_BOOT_ADMIN_CLIENT_URL: "http://10.5.2.3:8082"
      SPRING_BOOT_ADMIN_CLIENT_INSTACE_ENABLED: "true"
      MANAGEMENT_HEALTH_DISKSPACE: "true"
      MANAGEMENT_INFO_ENV_ENABLED: "true"
      MANAGEMENT_INFO_GIT_MODE: "full"
      MANAGEMENT_INFO_GIT_ENABLED: "true"
      MANAGEMENT_INFO_OS_ENABLED: "true"
      MANAGEMENT_INFO_BUILD_ENABLED: "true"
      MANAGEMENT_ENDPOINT_HEALTH_SHOW-DETAILDS: "always"
      MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
      MANAGEMENT_ENDPOINT_INFO_ENABLED: "true"
      MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED: "true"
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "*"
      MANAGEMENT_ENDPOINTS_JMX_EXPOSURE_INCLUDE: "*"
      MANAGEMENT_ENDPOINTS_METRICS_ENABLE_ALL: "true"
      MANAGEMENT_INFO_ENABLED: "true"
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: "TRACE"
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_HTTP: "TRACE"
    ports:
      - 8083:8083
      - 8991:8991
    networks:
      lan-java-mongo-prometheus-grafana:
        ipv4_address: 10.5.2.2

  spring-boot-admin:
    image: spring-boot-admin-java17:0.0.1-SNAPSHOT
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '200M'
    ports:
      - 8082:8082
    networks:
      lan-java-mongo-prometheus-grafana:
        ipv4_address: 10.5.2.3
    environment:
      SERVER_ADDRESS: "10.5.2.3"
      SERVER_PORT: "8082"
      MANAGEMENT_HEALTH_DISKSPACE: "true"
      MANAGEMENT_INFO_ENV_ENABLED: "true"
      MANAGEMENT_INFO_GIT_MODE: "full"
      MANAGEMENT_INFO_GIT_ENABLED: "true"
      MANAGEMENT_INFO_OS_ENABLED: "true"
      MANAGEMENT_INFO_BUILD_ENABLED: "true"
      MANAGEMENT_ENDPOINT_HEALTH_SHOW-DETAILDS: "always"
      MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
      MANAGEMENT_ENDPOINT_INFO_ENABLED: "true"
      MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED: "true"
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "*"
      MANAGEMENT_ENDPOINTS_JMX_EXPOSURE_INCLUDE: "*"
      MANAGEMENT_ENDPOINTS_METRICS_ENABLE_ALL: "true"
      MANAGEMENT_INFO_ENABLED: "true"
networks:
  lan-java-mongo-prometheus-grafana:
    driver: bridge
    ipam:
      config:
      - subnet: 10.5.0.0/16
        gateway: 10.5.0.1
