
spring:
  jmx:
    enabled: true
    unique-names: true
  boot:
    admin:
      client:
        url: "http://localhost:8081"
        instance:
          name: "@project.artifactId@"
        enabled: true
  datasource:
    username: manager
    password: 1234
    hikari:
      connection-timeout: 50000
      idle-timeout: 300000
      max-lifetime: 900000
      maximum-pool-size: 3
      minimum-idle: 1
      pool-name: UserManagerPool
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://10.5.0.3:5433/user_manager"
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      connection:
        provider_class: "org.hibernate.hikaricp.internal.HikariCPConnectionProvider"
    show-sql: true
jwt:
  secret:
    access: "qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w=="
    life-time: 100
server:
  port: 8084

management:
  health:
    diskspace:
      enabled: true
  datadog:
    metrics:
      export:
        enabled: true
  info:
    env:
      enabled: true
    git:
      mode: full
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
    build:
      enabled: true
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    info:
      enabled: true
    env:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"
  metrics:
    enable:
      spring: true
  server:
    port: 8091
info:
  app:
    encoding: "@project.build.sourceEncoding@"
    java:
      source: "@java.version@"
      target: "@java.version@"